# Generated by Django 3.1.4 on 2020-12-29 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('is_qa', models.BooleanField()),
                ('is_project', models.BooleanField()),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Capstone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_url', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='LearningAPI.book')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown_text', models.TextField()),
                ('public', models.BooleanField()),
                ('date', models.DateField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('slack_channel', models.CharField(max_length=55)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('break_start_date', models.DateField()),
                ('break_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swbat', models.CharField(max_length=255)),
                ('bloom_level', models.CharField(choices=[('REM', 'Remember'), ('UND', 'Understand'), ('APP', 'Apply'), ('ANZ', 'Analyze'), ('EVL', 'Evaluate'), ('CRT', 'Create')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LightningExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NssUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_handle', models.CharField(blank=True, max_length=55, null=True)),
                ('github_handle', models.CharField(blank=True, max_length=55, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('implementation_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.CharField(max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='LearningAPI.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='LearningAPI.nssuser')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.capstone')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='LearningAPI.nssuser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='LearningAPI.nssuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecttags', to='LearningAPI.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecttags', to='LearningAPI.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.nssuser')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectivetags', to='LearningAPI.learningobjective')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectivetags', to='LearningAPI.tag')),
            ],
        ),
        migrations.CreateModel(
            name='NssUserCohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.cohort')),
                ('nss_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.nssuser')),
            ],
        ),
        migrations.CreateModel(
            name='LightningTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightningtags', to='LearningAPI.lightningexercise')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightningtags', to='LearningAPI.tag')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.chapternote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.nssuser')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='LearningAPI.chapter')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='LearningAPI.learningobjective')),
            ],
        ),
        migrations.AddField(
            model_name='chapternote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.nssuser'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='LearningAPI.project'),
        ),
        migrations.CreateModel(
            name='CapstoneTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('capstone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.capstone')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.proposalstatus')),
            ],
        ),
        migrations.AddField(
            model_name='capstone',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.course'),
        ),
        migrations.AddField(
            model_name='capstone',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='capstones', to='LearningAPI.nssuser'),
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='LearningAPI.course'),
        ),
        migrations.CreateModel(
            name='AssessmentObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='LearningAPI.assessment')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='LearningAPI.learningobjective')),
            ],
        ),
    ]
