# Generated by Django 4.0.1 on 2022-02-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='is_project',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='is_qa',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='url',
        ),
        migrations.AddField(
            model_name='assessment',
            name='source_url',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('SELF', 'Self-assessment'), ('ASSIGNED', 'Assigned by instructor')], default='SELF', max_length=8),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=512)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.assessment')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='LearningAPI.nssuser')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.studentassessmentstatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assessments', to='LearningAPI.nssuser')),
            ],
            options={
                'unique_together': {('student', 'assessment')},
            },
        ),
    ]
