# Generated by Django 4.0.3 on 2022-03-22 16:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0002_studentassessmentstatus_remove_assessment_is_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CoreSkillRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('created_on', models.DateField(blank=True, default=datetime.date.today, editable=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_records', to='LearningAPI.coreskill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_records', to='LearningAPI.nssuser')),
            ],
        ),
        migrations.CreateModel(
            name='CoreSkillRecordEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('recorded_on', models.DateField(blank=True, default=datetime.date.today, editable=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='LearningAPI.nssuser')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to='LearningAPI.coreskillrecord')),
            ],
        ),
    ]
