# Generated by Django 4.0.3 on 2022-03-22 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0004_alter_coreskillrecord_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreskillrecord',
            name='level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
