# Generated by Django 4.0.3 on 2022-03-27 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0005_alter_coreskillrecord_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneononenote',
            options={'ordering': ['-session_date']},
        ),
        migrations.AlterField(
            model_name='coreskillrecordentry',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='LearningAPI.coreskillrecord'),
        ),
        migrations.AlterField(
            model_name='oneononenote',
            name='session_date',
            field=models.DateTimeField(),
        ),
    ]
