# Generated by Django 4.0.3 on 2022-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0006_alter_oneononenote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneononenote',
            name='session_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
