# Generated by Django 4.0.3 on 2022-03-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0007_alter_oneononenote_session_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.nssuser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='LearningAPI.nssuser')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
