# Generated by Django 4.0.3 on 2022-12-01 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0009_alter_learningrecordentry_options_capstone_repo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capstone',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='capstonetimeline',
            name='capstone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='statuses', to='LearningAPI.capstone'),
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='LearningAPI.assessment'),
        ),
    ]
