# Generated by Django 4.0.3 on 2022-12-06 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0010_alter_capstone_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='LearningAPI.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chapters', to='LearningAPI.nssuser')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentProject',
        ),
    ]
