# Generated by Django 4.0.3 on 2022-12-06 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0011_studentchapter_delete_studentproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='chapternote',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapternote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chapterobjective',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapterobjective',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='favoritenote',
            name='note',
        ),
        migrations.RemoveField(
            model_name='favoritenote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentchapter',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='studentchapter',
            name='student',
        ),
        migrations.AddField(
            model_name='project',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='LearningAPI.book'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='ChapterNote',
        ),
        migrations.DeleteModel(
            name='ChapterObjective',
        ),
        migrations.DeleteModel(
            name='FavoriteNote',
        ),
        migrations.DeleteModel(
            name='StudentChapter',
        ),
        migrations.AddField(
            model_name='studentproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='LearningAPI.project'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='LearningAPI.nssuser'),
        ),
    ]
