# Generated by Django 4.0.3 on 2022-12-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0013_book_cardinality'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
