# Generated by Django 4.0.3 on 2022-12-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0014_studentassessment_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.book'),
        ),
    ]
