# Generated by Django 4.0.3 on 2022-12-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0017_studentnote_delete_dailystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreskillrecord',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.coreskill'),
        ),
        migrations.AlterField(
            model_name='coreskillrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_skills', to='LearningAPI.nssuser'),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='LearningAPI.nssuser'),
        ),
    ]
