# Generated by Django 4.0.3 on 2022-12-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0018_alter_coreskillrecord_skill_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentproject',
            unique_together={('student', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='studenttag',
            unique_together={('student', 'tag')},
        ),
    ]
