# Generated by Django 4.0.3 on 2022-12-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0020_alter_assessment_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='LearningAPI.cohort')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='LearningAPI.course')),
            ],
            options={
                'unique_together': {('cohort', 'course')},
            },
        ),
    ]
