# Generated by Django 4.0.3 on 2022-12-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0023_project_cardinality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cardinality',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='cardinality',
            new_name='index',
        ),
    ]
