# Generated by Django 4.0.3 on 2023-01-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0025_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_organization_url', models.CharField(max_length=75, unique=True)),
                ('github_classroom_url', models.CharField(max_length=75, unique=True)),
                ('attendance_sheet_url', models.CharField(max_length=255, unique=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='LearningAPI.cohort')),
            ],
        ),
    ]
