# Generated by Django 4.0.3 on 2023-02-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0027_alter_cohortinfo_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortinfo',
            name='attendance_sheet_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cohortinfo',
            name='github_classroom_url',
            field=models.CharField(blank=True, max_length=75, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cohortinfo',
            name='student_organization_url',
            field=models.CharField(blank=True, max_length=75, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_projects', to='LearningAPI.book'),
        ),
    ]
