# Generated by Django 4.0.3 on 2023-01-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0028_alter_project_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
