# Generated by Django 4.0.3 on 2023-02-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0029_cohortcourse_index_course_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortcourse',
            name='index',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
