# Generated by Django 4.0.3 on 2023-01-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0025_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.book'),
        ),
    ]
