# Generated by Django 4.0.3 on 2023-02-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0030_cohortcourse_index_course_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_assignments', to='LearningAPI.assessment')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_assignments', to='LearningAPI.learningweight')),
            ],
        ),
    ]
