# Generated by Django 4.0.3 on 2023-02-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0031_assessmentweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='objectives',
            field=models.ManyToManyField(through='LearningAPI.AssessmentWeight', to='LearningAPI.learningweight'),
        ),
        migrations.AlterField(
            model_name='assessmentobjective',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentobjective',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningAPI.learningobjective'),
        ),
    ]
