# Generated by Django 4.2.2 on 2023-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0032_assessment_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortinfo',
            name='course_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
