# Generated by Django 4.0.3 on 2023-02-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0030_cohortcourse_index'),
        ('LearningAPI', '0033_alter_project_book'),
    ]

    operations = [
    ]
