# Generated by Django 4.2.2 on 2023-06-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0033_cohortinfo_course_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohortinfo',
            old_name='course_url',
            new_name='client_course_url',
        ),
        migrations.AddField(
            model_name='cohortinfo',
            name='server_course_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
