# Generated by Django 4.2.2 on 2023-06-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0034_rename_course_url_cohortinfo_client_course_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortinfo',
            name='zoom_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
