# Generated by Django 4.2.2 on 2023-09-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0035_cohortinfo_zoom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='slack_channel',
            field=models.CharField(max_length=55),
        ),
    ]
