# Generated by Django 4.2.5 on 2023-09-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0036_alter_cohort_slack_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortinfo',
            name='github_classroom_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cohortinfo',
            name='student_organization_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
