# Generated by Django 4.2.8 on 2024-01-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0038_course_active"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION get_project_average_start_delay(course_id_param INT)
            RETURNS TABLE(
                BookName character varying(75),
                BookIndex INT,
                ProjectName character varying(75),
                ProjectIndex INT,
                AverageStartDelay NUMERIC
            ) AS $$
            BEGIN
                RETURN QUERY
                SELECT book.name AS "BookName",
                    book.index AS "BookIndex",
                    project.name AS "ProjectName",
                    project.index AS "ProjectIndex",
                    AVG(student_project.date_created - cohort.start_date) AS "AverageStartDelay"
                FROM "LearningAPI_studentproject" AS student_project
                INNER JOIN "LearningAPI_project" AS project ON student_project.project_id = project.id
                INNER JOIN "LearningAPI_book" AS book ON project.book_id = book.id
                INNER JOIN "LearningAPI_nssusercohort" AS nssusercohort ON student_project.student_id = nssusercohort.nss_user_id
                INNER JOIN "LearningAPI_cohort" AS cohort ON nssusercohort.cohort_id = cohort.id
                INNER JOIN "LearningAPI_course" AS course ON book.course_id = course.id
                WHERE course.id = course_id_param
                GROUP BY book.index, book.name, project.index, project.name
                ORDER BY book.index, project.index;
            END;
            $$ LANGUAGE plpgsql;
            """,
            "DROP FUNCTION IF EXISTS get_project_average_start_delay(INT);"
        ),
    ]
