# Generated by Django 4.2.8 on 2024-02-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0039_add_project_stats_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capstonetimeline",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
