# Generated by Django 4.2.10 on 2024-04-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0042_alter_learningrecord_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
