# Generated by Django 4.2.11 on 2024-05-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0043_cohort_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
