# Generated by Django 4.2.11 on 2024-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0044_project_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_group_project",
            field=models.BooleanField(default=False),
        ),
    ]
