# Generated by Django 4.2.14 on 2024-09-03 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("LearningAPI", "0052_studentteam_nssuserteam_groupprojectrepository"),
        ("LearningAPI", "0053_alter_studentteam_group_name"),
        ("LearningAPI", "0054_alter_nssuserteam_student_alter_nssuserteam_team"),
        ("LearningAPI", "0055_studentteam_members_alter_nssuserteam_student_and_more"),
        ("LearningAPI", "0056_rename_members_studentteam_students"),
        ("LearningAPI", "0057_project_template_url"),
        (
            "LearningAPI",
            "0058_remove_project_template_url_project_api_template_url_and_more",
        ),
        ("LearningAPI", "0059_remove_groupprojectrepository_repository_url"),
        ("LearningAPI", "0060_studentteam_slack_channel"),
    ]

    dependencies = [
        ("LearningAPI", "0051_add_student_note_type_to_database_function"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTeam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=55)),
                ("sprint_team", models.BooleanField(default=False)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LearningAPI.cohort",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NSSUserTeam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LearningAPI.nssuser",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="LearningAPI.studentteam",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentteam",
            name="students",
            field=models.ManyToManyField(
                through="LearningAPI.NSSUserTeam", to="LearningAPI.nssuser"
            ),
        ),
        migrations.AlterField(
            model_name="nssuserteam",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="LearningAPI.studentteam",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="api_template_url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="client_template_url",
            field=models.URLField(default=""),
        ),
        migrations.CreateModel(
            name="GroupProjectRepository",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LearningAPI.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LearningAPI.studentteam",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentteam",
            name="slack_channel",
            field=models.CharField(default="", max_length=55),
        ),
    ]
