# Generated by Django 4.2.14 on 2024-08-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0052_studentteam_nssuserteam_groupprojectrepository"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentteam",
            name="group_name",
            field=models.CharField(max_length=55),
        ),
    ]
