# Generated by Django 4.2.14 on 2024-08-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0053_alter_studentteam_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nssuserteam",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="LearningAPI.nssuser",
            ),
        ),
        migrations.AlterField(
            model_name="nssuserteam",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="LearningAPI.studentteam",
            ),
        ),
    ]
