# Generated by Django 4.2.14 on 2024-08-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0054_alter_nssuserteam_student_alter_nssuserteam_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentteam",
            name="members",
            field=models.ManyToManyField(
                through="LearningAPI.NSSUserTeam", to="LearningAPI.nssuser"
            ),
        ),
        migrations.AlterField(
            model_name="nssuserteam",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="LearningAPI.nssuser"
            ),
        ),
        migrations.AlterField(
            model_name="nssuserteam",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="LearningAPI.studentteam",
            ),
        ),
    ]
