# Generated by Django 4.2.14 on 2024-08-28 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0055_studentteam_members_alter_nssuserteam_student_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentteam",
            old_name="members",
            new_name="students",
        ),
    ]
