# Generated by Django 4.2.14 on 2024-08-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0057_project_template_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="template_url",
        ),
        migrations.AddField(
            model_name="project",
            name="api_template_url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="client_template_url",
            field=models.URLField(default=""),
        ),
    ]
