# Generated by Django 4.2.14 on 2024-08-29 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "LearningAPI",
            "0058_remove_project_template_url_project_api_template_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupprojectrepository",
            name="repository_url",
        ),
    ]
