# Generated by Django 4.2.14 on 2024-08-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0059_remove_groupprojectrepository_repository_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentteam",
            name="slack_channel",
            field=models.CharField(default="", max_length=55),
        ),
    ]
