# Generated by Django 4.2.14 on 2024-10-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0061_groupprojectrepository_repository"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupprojectrepository",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to="LearningAPI.studentteam",
            ),
        ),
    ]
