# Generated by Django 4.2.14 on 2024-12-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0062_alter_groupprojectrepository_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentInterview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_completed", models.DateField(auto_created=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="LearningAPI.nssuser",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviewers",
                        to="LearningAPI.nssuser",
                    ),
                ),
            ],
        ),
    ]
