# Generated by Django 4.2.17 on 2025-01-01 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0050_helpcategory_helprequest_helptag_requestquery_and_more"),
        ("LearningAPI", "0062_alter_groupprojectrepository_team"),
    ]

    operations = []
