# Generated by Django 4.2.14 on 2024-12-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0063_studentinterview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinterview",
            name="date_completed",
            field=models.DateField(auto_now_add=True),
        ),
    ]
