# Generated by Django 4.2.17 on 2025-01-21 02:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0063_merge_20250101_0406"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helprequestresponse",
            name="author",
        ),
        migrations.RemoveField(
            model_name="helprequestresponse",
            name="help_request",
        ),
        migrations.AlterUniqueTogether(
            name="helprequesttag",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="helprequesttag",
            name="help_request",
        ),
        migrations.RemoveField(
            model_name="helprequesttag",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="requestquery",
            name="helpful_request",
        ),
        migrations.RemoveField(
            model_name="requestquery",
            name="searcher",
        ),
        migrations.RenameField(
            model_name="helprequest",
            old_name="content",
            new_name="question",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="author",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="category",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="exception_message",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="github_url",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="is_resolved",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="llm_prompt",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="loom_url",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="stack_trace",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="title",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="helprequest",
            name="status",
            field=models.CharField(default="invalid", max_length=20),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="LearningAPI.nssuser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="HelpCategory",
        ),
        migrations.DeleteModel(
            name="HelpRequestResponse",
        ),
        migrations.DeleteModel(
            name="HelpRequestTag",
        ),
        migrations.DeleteModel(
            name="HelpTag",
        ),
        migrations.DeleteModel(
            name="RequestQuery",
        ),
    ]
