# Generated by Django 4.2.17 on 2025-04-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0063_merge_20250101_0406"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundationsExercise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learner_github_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=75)),
                ("slug", models.SlugField(max_length=75)),
                ("attempts", models.IntegerField(default=0)),
                ("complete", models.BooleanField(default=False)),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("first_attempt", models.DateField(blank=True, null=True)),
                ("last_attempt", models.DateField(blank=True, null=True)),
                ("completed_code", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
