# Generated by Django 4.2.17 on 2025-04-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0064_foundationsexercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="foundationsexercise",
            name="learner_name",
            field=models.CharField(default="", max_length=75),
            preserve_default=False,
        ),
    ]
