# Generated by Django 4.2.17 on 2025-04-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0065_foundationsexercise_learner_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helprequest",
            name="author",
        ),
        migrations.RemoveField(
            model_name="helprequest",
            name="category",
        ),
        migrations.RemoveField(
            model_name="helprequestresponse",
            name="author",
        ),
        migrations.RemoveField(
            model_name="helprequestresponse",
            name="help_request",
        ),
        migrations.AlterUniqueTogether(
            name="helprequesttag",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="helprequesttag",
            name="help_request",
        ),
        migrations.RemoveField(
            model_name="helprequesttag",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="requestquery",
            name="helpful_request",
        ),
        migrations.RemoveField(
            model_name="requestquery",
            name="searcher",
        ),
        migrations.DeleteModel(
            name="HelpCategory",
        ),
        migrations.DeleteModel(
            name="HelpRequest",
        ),
        migrations.DeleteModel(
            name="HelpRequestResponse",
        ),
        migrations.DeleteModel(
            name="HelpRequestTag",
        ),
        migrations.DeleteModel(
            name="HelpTag",
        ),
        migrations.DeleteModel(
            name="RequestQuery",
        ),
    ]
