# Generated by Django 4.2.17 on 2025-04-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0066_remove_helprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="foundationsexercise",
            name="used_solution",
            field=models.BooleanField(default=False),
        ),
    ]
