# Generated by Django 4.2.17 on 2025-04-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0067_foundationsexercise_used_solution"),
    ]

    operations = [
        migrations.AddField(
            model_name="foundationsexercise",
            name="cohort",
            field=models.CharField(default="Unassigned", max_length=15),
        ),
    ]
