# Generated by Django 4.2.17 on 2025-05-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LearningAPI", "0068_foundationsexercise_cohort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foundationsexercise",
            name="completed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foundationsexercise",
            name="first_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foundationsexercise",
            name="last_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
