# Generated by Django 5.2.3 on 2025-06-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0070_foundationslearnerprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name of the event', max_length=255)),
                ('event_datetime', models.DateTimeField(help_text='Date and time of the event')),
                ('description', models.TextField(blank=True, help_text='Description of the event')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the event was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the event was last updated')),
                ('cohort', models.OneToOneField(help_text='The cohort this event is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='LearningAPI.cohort')),
            ],
        ),
    ]
