# Generated by Django 5.2.3 on 2025-06-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0071_cohortevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortevent',
            name='cohort',
            field=models.ForeignKey(help_text='The cohort this event is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='LearningAPI.cohort'),
        ),
    ]
