# Generated by Django 5.2.3 on 2025-06-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningAPI', '0073_cohorteventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortevent',
            name='event_type',
            field=models.ForeignKey(default=1, help_text='Type of the event (e.g., graduation, announcement)', on_delete=django.db.models.deletion.DO_NOTHING, to='LearningAPI.cohorteventtype'),
            preserve_default=False,
        ),
    ]
